import os


GOAL = 30
DELAY = 4

VISION_W = 1  # less than 7
VISION_F = 21  # less than 70
VISION_B = 14  # less than 30

VISUAL_VISION_W = 7  # less than 7
VISUAL_VISION_F = 21  # less than 70
VISUAL_VISION_B = 7  # less than 30

VISUALENABLED = True
DLAGENTENABLED = True
DL_IS_TRAINING = False

MAX_SIMULATION_CAR = 60

CONSTANT_PENALTY = -0

EMERGENCY_BRAKE_MAX_SPEED_DIFF = 20
EMERGENCY_BRAKE_PENALTY = float(os.environ.get('EMERGENCY_BRAKE_PENALTY', 0))

MISMATCH_ACTION_PENALTY = -0
SWITCHING_LANE_PENALTY = -0.00001

MAX_MEM = 1000000
MAX_EPISODE = 2000
MAX_FRAME_COUNT = 1000 * DELAY
TESTING_EPISODE = 200

LEARNING_RATE = float(os.environ.get('LEARNING_RATE', 0.0001))
BATCH_SIZE = int(os.environ.get('BATCH_SIZE', 32))
EPSILON_GREEDY_START_PROB = 1.0
EPSILON_GREEDY_END_PROB = 0.1
EPSILON_GREEDY_MAX_STATES = 1000 * 2000
EPSILON_GREEDY_TEST_PROB = 0.05
TARGET_NETWORK_UPDATE_FREQUENCY = 10000
LEARN_START = 100000

ROUND = int(os.environ.get('ROUND', 4))

IDENTIFIER = os.environ.get('IDENTIFIER', 'PA')

MODEL_NAME = '{}_R{}__DQN__lr={}_input=36-3_conv=2_FC=2_nn=100-5_batch={}'\
    .format(IDENTIFIER, ROUND, LEARNING_RATE, BATCH_SIZE)

ROAD_VIEW_OFFSET = 1010
INPUT_VIEW_OFFSET_X = 1405
INPUT_VIEW_OFFSET_Y = 320
